version: '3.8'

services:

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    env_file:
      - .env
    networks:
      - master
    volumes:
      - redis-data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      #    host : container
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    # Comment the line below for production
    command: uvicorn backend.app.main:app --host ${APP_HOST} --port ${APP_PORT} --reload-dir /app --reload
    networks:
      - master
    volumes:
      - ./backend/app:/app/backend/app
      - ./frontend:/app/frontend

volumes:
  redis-data:

networks:
  master:
